# Generated by Django 5.2.6 on 2025-09-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_alter_cashflow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds.status', verbose_name='Статус'),
        ),
    ]
